Enable/disable sudo for gameuser when installing game.

diff --git a/overlay/usr/local/bin/gameserver-init b/overlay/usr/local/bin/gameserver-init
--- a/overlay/usr/local/bin/gameserver-init
+++ b/overlay/usr/local/bin/gameserver-init
@@ -6,6 +6,16 @@ GAME_REPO_DIR="/root/gameservers"
 
 fatal() { echo "FATAL: $@"; exit 1; }
 
+clean_finish() {
+    sed -i "\|^$GAMEUSER| s|^|#|" /etc/sudoers
+    if [[ $1 -ne 0 ]]; then
+        echo
+        fatal "Install was interrupted and/or failed."
+    else
+        echo "Installation complete."
+    fi
+}
+
 select_game_interactive() {
     python3 "/usr/local/bin/gameserver-menu.py" "$GAME_REPO_DIR"
 }
@@ -26,7 +36,6 @@ select_game() {
             [[ -n $(stty size) ]] || exit 0
             select_game_interactive
         fi
-        
         echo 'GameServer: $ipaddr' | cat - /etc/confconsole/services.txt > temp_confconsole
         mv temp_confconsole /etc/confconsole/services.txt
     fi
@@ -38,17 +47,24 @@ install_game() {
         [[ -f "$conf" ]] || fatal "Conf file ($conf) not found."
         . $conf
 
+        unset exit_code
         cd "$GAME_REPO_DIR"
         chmod +x "auto_install.sh"
-        bash "./auto_install.sh" -g "$GAME" -u "$GAMEUSER" -p "/home/$GAMEUSER/gameserver"
-        
-        touch "/etc/gameserver/installation.done"
-
+        bash "./auto_install.sh" -g "$GAME" -u "$GAMEUSER" -p "/home/$GAMEUSER/gameserver" \
+            || exit_code=$?
+        if [[ -z exit_code ]]; then
+            touch "/etc/gameserver/installation.done"
+        else
+            fatal "Install failed. Please check previous logs for details."
+        fi
         # Enable server start on boot
         systemctl enable gameserver
     fi
     systemctl start gameserver
 }
 
+trap "clean_finish 1" INT TERM ERR
+sed -i "\|$GAMEUSER| s|^\s*#||" /etc/sudoers
 select_game
 install_game 2>&1 | tee -a "$LOGFILE"
+clean_finish 0
